# Generated by Django 2.0.6 on 2018-08-23 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flujo_vehicular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horacaptura', models.TimeField()),
                ('camara', models.CharField(max_length=30)),
                ('rutaimagen', models.ImageField(blank=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_negra_vehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('marca', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('anio_matricula', models.CharField(max_length=50, null=True)),
                ('modelo', models.CharField(max_length=100, null=True)),
                ('clase', models.CharField(max_length=50, null=True)),
                ('fecha_matricula', models.CharField(max_length=50, null=True)),
                ('anio_vehiculo', models.CharField(max_length=50, null=True)),
                ('servicio', models.CharField(max_length=50, null=True)),
                ('fecha_caducidad', models.CharField(max_length=50, null=True)),
                ('rutaimagen', models.ImageField(blank=True, upload_to='imagenes')),
            ],
        ),
        migrations.AddField(
            model_name='lista_negra_vehiculos',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo'),
        ),
        migrations.AddField(
            model_name='flujo_vehicular',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo'),
        ),
    ]
