# Generated by Django 2.0.6 on 2018-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('horacaptura', models.CharField(max_length=20)),
                ('camara', models.CharField(max_length=30)),
            ],
        ),
    ]
