# Generated by Django 2.0.6 on 2018-08-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='rutaimagen',
        ),
    ]
