# Generated by Django 2.0.6 on 2018-07-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('anio_matricula', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('clase', models.CharField(max_length=50)),
                ('fecha_matricula', models.CharField(max_length=50)),
                ('anio_vehiculo', models.CharField(max_length=50)),
                ('servicio', models.CharField(max_length=50)),
                ('fecha_caducidad', models.CharField(max_length=50)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_negra_vehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo')),
            ],
        ),
    ]
